import type { Exercise } from '@/types/exercise'

/**
 * Built-in exercise library.
 * Covers the most popular compound lifts and common accessories.
 * All exercises with isCustom: false.
 */
export const PREDEFINED_EXERCISES: Exercise[] = [
  // ── BARBELL — BIG LIFTS (Wilks-ranked) ──────────────────────────────

  {
    id: 'barbell_squat',
    name: 'Barbell Squat',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'quadriceps',
    secondaryMuscleGroups: ['glutes', 'hamstrings', 'lower_back', 'core'],
    useWilksRank: true,
    defaultSets: 5,
    defaultReps: 5,
    defaultWeight: 60,
    defaultRestSeconds: 180,
    notes: 'Stopy na szerokość barków, kolana nad palcami, biodra poniżej kolan.',
  },
  {
    id: 'barbell_bench_press',
    name: 'Bench Press',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['triceps', 'front_delts'],
    useWilksRank: true,
    defaultSets: 5,
    defaultReps: 5,
    defaultWeight: 50,
    defaultRestSeconds: 180,
    notes: 'Łopatki ściągnięte i oparte o ławkę, naturalny łuk lędźwiowy.',
  },
  {
    id: 'barbell_deadlift',
    name: 'Deadlift',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'lower_back',
    secondaryMuscleGroups: ['glutes', 'hamstrings', 'traps', 'forearms', 'quadriceps'],
    useWilksRank: true,
    defaultSets: 1,
    defaultReps: 5,
    defaultWeight: 80,
    defaultRestSeconds: 240,
    notes: 'Sztanga blisko nóg przez cały ruch, neutralna szyja.',
  },
  {
    id: 'barbell_ohp',
    name: 'Overhead Press',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'upper_back', 'core'],
    useWilksRank: true,
    defaultSets: 5,
    defaultReps: 5,
    defaultWeight: 40,
    defaultRestSeconds: 180,
    notes: 'Wyciśnij pionowo, przesuń głowę do przodu gdy sztanga mija czoło.',
  },
  {
    id: 'barbell_row',
    name: 'Barbell Row',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['upper_back', 'biceps', 'rear_delts', 'core'],
    useWilksRank: true,
    defaultSets: 5,
    defaultReps: 5,
    defaultWeight: 50,
    defaultRestSeconds: 180,
    notes: 'Tors równoległy do podłogi, sztanga do dolnych żeber.',
  },
  {
    id: 'barbell_sumo_deadlift',
    name: 'Sumo Deadlift',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'glutes',
    secondaryMuscleGroups: ['quadriceps', 'hamstrings', 'lower_back', 'adductors'],
    useWilksRank: true,
    defaultSets: 3,
    defaultReps: 5,
    defaultWeight: 80,
    defaultRestSeconds: 240,
  },
  {
    id: 'barbell_rdl',
    name: 'Romanian Deadlift',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'hamstrings',
    secondaryMuscleGroups: ['glutes', 'lower_back'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 60,
    defaultRestSeconds: 120,
  },
  {
    id: 'barbell_front_squat',
    name: 'Front Squat',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'quadriceps',
    secondaryMuscleGroups: ['glutes', 'core', 'upper_back'],
    useWilksRank: true,
    defaultSets: 4,
    defaultReps: 4,
    defaultWeight: 50,
    defaultRestSeconds: 180,
  },
  {
    id: 'barbell_incline_bench',
    name: 'Incline Bench Press',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['front_delts', 'triceps'],
    useWilksRank: true,
    defaultSets: 4,
    defaultReps: 6,
    defaultWeight: 40,
    defaultRestSeconds: 150,
  },
  {
    id: 'barbell_close_grip_bench',
    name: 'Close-Grip Bench Press',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'triceps',
    secondaryMuscleGroups: ['chest', 'front_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 40,
    defaultRestSeconds: 120,
  },
  {
    id: 'barbell_hip_thrust',
    name: 'Barbell Hip Thrust',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'glutes',
    secondaryMuscleGroups: ['hamstrings', 'core'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 60,
    defaultRestSeconds: 120,
  },
  {
    id: 'barbell_good_morning',
    name: 'Good Morning',
    isCustom: false,
    category: 'barbell',
    primaryMuscleGroup: 'hamstrings',
    secondaryMuscleGroups: ['lower_back', 'glutes'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 30,
    defaultRestSeconds: 90,
  },

  // ── DUMBBELL ─────────────────────────────────────────────────────────

  {
    id: 'db_bench_press',
    name: 'Dumbbell Bench Press',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['triceps', 'front_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 20,
    defaultRestSeconds: 120,
    notes: 'Waga per hantel.',
  },
  {
    id: 'db_shoulder_press',
    name: 'Dumbbell Shoulder Press',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'shoulders',
    secondaryMuscleGroups: ['triceps', 'traps'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 16,
    defaultRestSeconds: 90,
  },
  {
    id: 'db_row',
    name: 'Dumbbell Row',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'rear_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 24,
    defaultRestSeconds: 90,
  },
  {
    id: 'db_lateral_raise',
    name: 'Lateral Raise',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'side_delts',
    secondaryMuscleGroups: [],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 8,
    defaultRestSeconds: 60,
  },
  {
    id: 'db_front_raise',
    name: 'Front Raise',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'front_delts',
    secondaryMuscleGroups: ['side_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 8,
    defaultRestSeconds: 60,
  },
  {
    id: 'db_curl',
    name: 'Dumbbell Curl',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 12,
    defaultRestSeconds: 60,
  },
  {
    id: 'db_hammer_curl',
    name: 'Hammer Curl',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 14,
    defaultRestSeconds: 60,
  },
  {
    id: 'db_tricep_extension',
    name: 'Dumbbell Tricep Extension',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'triceps',
    secondaryMuscleGroups: [],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 12,
    defaultRestSeconds: 60,
  },
  {
    id: 'db_bulgarian_split_squat',
    name: 'Bulgarian Split Squat',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'quadriceps',
    secondaryMuscleGroups: ['glutes', 'hamstrings'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 16,
    defaultRestSeconds: 90,
    notes: 'Waga per hantel. Tylna noga na ławce.',
  },
  {
    id: 'db_romanian_deadlift',
    name: 'Dumbbell RDL',
    isCustom: false,
    category: 'dumbbell',
    primaryMuscleGroup: 'hamstrings',
    secondaryMuscleGroups: ['glutes', 'lower_back'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 20,
    defaultRestSeconds: 90,
  },

  // ── BODYWEIGHT (rep-ranked) ───────────────────────────────────────────

  {
    id: 'pull_up',
    name: 'Pull-Up',
    isCustom: false,
    category: 'bodyweight',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'rear_delts', 'upper_back'],
    useWilksRank: false, // uses rep-based rank
    defaultSets: 3,
    defaultReps: 8,
    defaultRestSeconds: 120,
    notes: 'Pełen zakres ruchu: wiszenie z wyprostowanymi ramionami → broda powyżej drążka.',
  },
  {
    id: 'chin_up',
    name: 'Chin-Up',
    isCustom: false,
    category: 'bodyweight',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'upper_back'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 8,
    defaultRestSeconds: 120,
    notes: 'Chwyt podchwytem (supinacja).',
  },
  {
    id: 'dip',
    name: 'Dip',
    isCustom: false,
    category: 'bodyweight',
    primaryMuscleGroup: 'triceps',
    secondaryMuscleGroups: ['chest', 'front_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultRestSeconds: 120,
    notes: 'Pełen zakres: 90° w łokciu w dole.',
  },
  {
    id: 'push_up',
    name: 'Push-Up',
    isCustom: false,
    category: 'bodyweight',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['triceps', 'front_delts', 'core'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultRestSeconds: 90,
  },
  {
    id: 'inverted_row',
    name: 'Inverted Row',
    isCustom: false,
    category: 'bodyweight',
    primaryMuscleGroup: 'upper_back',
    secondaryMuscleGroups: ['lats', 'biceps', 'rear_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultRestSeconds: 90,
  },
  {
    id: 'weighted_pull_up',
    name: 'Weighted Pull-Up',
    isCustom: false,
    category: 'bodyweight',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'rear_delts', 'upper_back'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 5,
    defaultWeight: 10,
    defaultRestSeconds: 150,
  },
  {
    id: 'weighted_chin_up',
    name: 'Weighted Chin-Up',
    isCustom: false,
    category: 'bodyweight',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'upper_back'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 5,
    defaultWeight: 10,
    defaultRestSeconds: 150,
  },
  {
    id: 'weighted_dip',
    name: 'Weighted Dip',
    isCustom: false,
    category: 'bodyweight',
    primaryMuscleGroup: 'triceps',
    secondaryMuscleGroups: ['chest', 'front_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 6,
    defaultWeight: 10,
    defaultRestSeconds: 150,
  },

  // ── MACHINE ──────────────────────────────────────────────────────────

  {
    id: 'lat_pulldown',
    name: 'Lat Pulldown',
    isCustom: false,
    category: 'machine',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps', 'rear_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 50,
    defaultRestSeconds: 90,
  },
  {
    id: 'leg_press',
    name: 'Leg Press',
    isCustom: false,
    category: 'machine',
    primaryMuscleGroup: 'quadriceps',
    secondaryMuscleGroups: ['glutes', 'hamstrings'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 100,
    defaultRestSeconds: 120,
  },
  {
    id: 'leg_curl',
    name: 'Leg Curl (Machine)',
    isCustom: false,
    category: 'machine',
    primaryMuscleGroup: 'hamstrings',
    secondaryMuscleGroups: [],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 40,
    defaultRestSeconds: 90,
  },
  {
    id: 'leg_extension',
    name: 'Leg Extension',
    isCustom: false,
    category: 'machine',
    primaryMuscleGroup: 'quadriceps',
    secondaryMuscleGroups: [],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 40,
    defaultRestSeconds: 90,
  },
  {
    id: 'chest_press_machine',
    name: 'Chest Press (Machine)',
    isCustom: false,
    category: 'machine',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['triceps', 'front_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 50,
    defaultRestSeconds: 90,
  },
  {
    id: 'seated_row_machine',
    name: 'Seated Row (Machine)',
    isCustom: false,
    category: 'machine',
    primaryMuscleGroup: 'upper_back',
    secondaryMuscleGroups: ['lats', 'biceps'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 50,
    defaultRestSeconds: 90,
  },
  {
    id: 'hack_squat',
    name: 'Hack Squat',
    isCustom: false,
    category: 'machine',
    primaryMuscleGroup: 'quadriceps',
    secondaryMuscleGroups: ['glutes', 'hamstrings'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 80,
    defaultRestSeconds: 120,
  },
  {
    id: 'calf_raise_machine',
    name: 'Calf Raise (Machine)',
    isCustom: false,
    category: 'machine',
    primaryMuscleGroup: 'calves',
    secondaryMuscleGroups: [],
    useWilksRank: false,
    defaultSets: 4,
    defaultReps: 15,
    defaultWeight: 60,
    defaultRestSeconds: 60,
  },
  {
    id: 'pec_deck',
    name: 'Pec Deck / Chest Fly',
    isCustom: false,
    category: 'machine',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['front_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 40,
    defaultRestSeconds: 60,
  },

  // ── CABLE ────────────────────────────────────────────────────────────

  {
    id: 'cable_row',
    name: 'Cable Row',
    isCustom: false,
    category: 'cable',
    primaryMuscleGroup: 'upper_back',
    secondaryMuscleGroups: ['lats', 'biceps'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 40,
    defaultRestSeconds: 90,
  },
  {
    id: 'cable_pulldown',
    name: 'Cable Pulldown',
    isCustom: false,
    category: 'cable',
    primaryMuscleGroup: 'lats',
    secondaryMuscleGroups: ['biceps'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 40,
    defaultRestSeconds: 90,
  },
  {
    id: 'cable_fly',
    name: 'Cable Fly',
    isCustom: false,
    category: 'cable',
    primaryMuscleGroup: 'chest',
    secondaryMuscleGroups: ['front_delts'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 15,
    defaultRestSeconds: 60,
  },
  {
    id: 'cable_tricep_pushdown',
    name: 'Tricep Pushdown',
    isCustom: false,
    category: 'cable',
    primaryMuscleGroup: 'triceps',
    secondaryMuscleGroups: [],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 20,
    defaultRestSeconds: 60,
  },
  {
    id: 'cable_bicep_curl',
    name: 'Cable Curl',
    isCustom: false,
    category: 'cable',
    primaryMuscleGroup: 'biceps',
    secondaryMuscleGroups: ['forearms'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 15,
    defaultRestSeconds: 60,
  },
  {
    id: 'cable_face_pull',
    name: 'Face Pull',
    isCustom: false,
    category: 'cable',
    primaryMuscleGroup: 'rear_delts',
    secondaryMuscleGroups: ['upper_back', 'traps'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 15,
    defaultRestSeconds: 60,
    notes: 'Linka na poziomie twarzy, łokcie powyżej nadgarstków.',
  },
  {
    id: 'cable_lateral_raise',
    name: 'Cable Lateral Raise',
    isCustom: false,
    category: 'cable',
    primaryMuscleGroup: 'side_delts',
    secondaryMuscleGroups: [],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 8,
    defaultRestSeconds: 60,
  },
  
  // ── CARDIO / ISOMETRIC (time-based) ──────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    isCustom: false,
    category: 'bodyweight',
    primaryMuscleGroup: 'core',
    secondaryMuscleGroups: ['shoulders'],
    useWilksRank: false,
    defaultSets: 3,
    defaultReps: 0,
    defaultRestSeconds: 60,
    type: 'time',
  },
  {
    id: 'treadmill_run',
    name: 'Treadmill Run',
    isCustom: false,
    category: 'cardio',
    primaryMuscleGroup: 'quadriceps',
    secondaryMuscleGroups: ['calves', 'glutes', 'hamstrings'],
    useWilksRank: false,
    defaultSets: 1,
    defaultReps: 0,
    defaultRestSeconds: 0,
    type: 'time',
  },
]

/**
 * Helper: find a predefined exercise by its id.
 */
export function findExerciseById(id: string): Exercise | undefined {
  return PREDEFINED_EXERCISES.find((e) => e.id === id)
}
